use std::env;
use std::fs;
use std::path::Path;

fn main() {
    tauri_build::build();

    // Generate embedded knowledge index from study/knowledge/*.md files
    let knowledge_dir = Path::new("../study/knowledge");
    if !knowledge_dir.exists() {
        println!("cargo:warning=Knowledge directory not found at {:?}", knowledge_dir);
        return;
    }

    let mut entries: Vec<String> = Vec::new();
    walk_dir(knowledge_dir, &mut entries);

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("knowledge_data.rs");

    let mut code = String::from(
        "// Auto-generated by build.rs — do not edit\n\n\
         pub fn embedded_knowledge() -> &'static [KnowledgeEntry] {\n\
         \x20   &[\n",
    );

    for entry in entries {
        code.push_str(&entry);
    }

    code.push_str("    ]\n}\n");

    fs::write(&dest_path, code).expect("Failed to write knowledge_data.rs");
    println!("cargo:rerun-if-changed=../study/knowledge");
}

fn walk_dir(dir: &Path, entries: &mut Vec<String>) {
    if let Ok(iter) = fs::read_dir(dir) {
        let mut files: Vec<_> = iter.filter_map(|e| e.ok()).collect();
        files.sort_by_key(|e| e.file_name());

        for entry in files {
            let path = entry.path();
            if path.is_dir() {
                walk_dir(&path, entries);
            } else if path.extension().map_or(false, |e| e == "md") {
                if let Some(entry_code) = process_file(&path) {
                    entries.push(entry_code);
                }
            }
        }
    }
}

fn process_file(path: &Path) -> Option<String> {
    let content = fs::read_to_string(path).ok()?;

    // Parse frontmatter between --- delimiters
    let mut title = String::new();
    let mut tags = String::new();
    let mut body_start = 0;

    let mut in_frontmatter = false;
    let mut frontmatter_closed = false;

    for (i, line) in content.lines().enumerate() {
        if i == 0 && line.trim() == "---" {
            in_frontmatter = true;
            continue;
        }
        if in_frontmatter && !frontmatter_closed {
            if line.trim() == "---" {
                frontmatter_closed = true;
                body_start = i + 1;
                continue;
            }
            let trimmed = line.trim();
            if trimmed.starts_with("title:") {
                title = trimmed.trim_start_matches("title:").trim().trim_matches('"').to_string();
            }
            if trimmed.starts_with("tags:") {
                tags = trimmed.trim_start_matches("tags:").trim().to_string();
            }
        }
    }

    let body: String = content.lines().skip(body_start).collect::<Vec<_>>().join("\\n");

    // Escape Rust string
    let body = body.replace('\\', "\\\\").replace('"', "\\\"");
    let title = title.replace('\\', "\\\\").replace('"', "\\\"");
    let tags = tags.replace('\\', "\\\\").replace('"', "\\\"");

    let rel_path = path.to_string_lossy().replace('\\', "/");

    Some(format!(
        "        KnowledgeEntry {{\n\
         \x20           file: \"{}\",\n\
         \x20           title: \"{}\",\n\
         \x20           tags: \"{}\",\n\
         \x20           content: \"{}\",\n\
         \x20       }},\n",
        rel_path, title, tags, body
    ))
}
